// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvV1WX5ITeGbieZB9TtMT8cJmrtQ4Amn8',
    appId: '1:88442310743:web:b71f3e6dd913f63b055312',
    messagingSenderId: '88442310743',
    projectId: 'firbase-app-2',
    authDomain: 'firbase-app-2.firebaseapp.com',
    storageBucket: 'firbase-app-2.appspot.com',
    measurementId: 'G-P5H5RYCZXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7ryKSGobjO78y1IJ2YhSHx-8T_Ymn1dg',
    appId: '1:88442310743:android:ad0670dc0464155f055312',
    messagingSenderId: '88442310743',
    projectId: 'firbase-app-2',
    storageBucket: 'firbase-app-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA074236Zm9LOac2zwtrjXnGawskDh9UkE',
    appId: '1:88442310743:ios:fefd88f445b14252055312',
    messagingSenderId: '88442310743',
    projectId: 'firbase-app-2',
    storageBucket: 'firbase-app-2.appspot.com',
    iosClientId: '88442310743-v7maolj742iinabdhktdod6vaqniq52o.apps.googleusercontent.com',
    iosBundleId: 'flutter',
  );
}
